
# tap repositories and their packages

tap 'homebrew/core'
brew 'ansible'
brew 'aspell'
brew 'autoconf'
brew 'autojump'
brew 'automake'
brew 'bash-completion'
brew 'boost'
brew 'bsdmake'
brew 'cairo'
brew 'cmake'
brew 'cmigemo'
brew 'colordiff'
brew 'coreutils'
brew 'cscope'
brew 'ctop'
brew 'digdag'
brew 'direnv'
brew 'docker-clean'
brew 'eigen'
brew 'elinks'
brew 'embulk'
brew 'fish'
brew 'fontconfig'
brew 'fontforge'
brew 'freetype'
brew 'fribidi'
brew 'fzf'
brew 'gcc'
brew 'gdbm'
brew 'gettext'
brew 'ghq'
brew 'giflib'
brew 'git'
brew 'glib'
brew 'gmp'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnutls'
brew 'go'
brew 'gradle'
brew 'graphite2'
brew 'grep'
brew 'hadolint'
brew 'harfbuzz'
brew 'htop'
brew 'httping'
brew 'hub'
brew 'icu4c'
brew 'iproute2mac'
brew 'isl'
brew 'jemalloc'
brew 'jmeter'
brew 'jpeg'
brew 'jq'
brew 'kompose'
brew 'kubernetes-cli'
brew 'lazygit'
brew 'libevent'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libidn2'
brew 'libmpc'
brew 'libpng'
brew 'libspiro'
brew 'libssh2'
brew 'libtasn1'
brew 'libtermkey'
brew 'libtiff'
brew 'libtool'
brew 'libuninameslist'
brew 'libunistring'
brew 'libusb'
brew 'libuv'
brew 'libvterm'
brew 'libyaml'
brew 'llvm'
brew 'lua'
brew 'luajit'
brew 'lz4'
brew 'lzo'
brew 'make'
brew 'mas'
brew 'maven'
brew 'mcrypt'
brew 'mecab'
brew 'mhash'
brew 'mosh'
brew 'mpfr'
brew 'msgpack'
brew 'mycli'
brew 'mysql@5.6'
brew 'mysql@5.7'
brew 'ncurses'
brew 'neovim'
brew 'nettle'
brew 'nginx'
brew 'nkf'
brew 'node'
brew 'nodebrew'
brew 'numpy'
brew 'oniguruma'
brew 'openblas'
brew 'openssl'
brew 'openvpn'
brew 'p11-kit'
brew 'pango'
brew 'pcre'
brew 'pcre2'
brew 'peco'
brew 'perl'
brew 'perl-build'
brew 'pixman'
brew 'pkcs11-helper'
brew 'pkg-config'
brew 'postgresql'
brew 'protobuf'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python'
brew 'python@2'
brew 'qemu'
brew 'rainbarf'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'redpen'
brew 'ripgrep'
brew 'ruby'
brew 'ruby-build'
brew 'rust'
brew 's3cmd'
brew 'sbt'
brew 'scala'
brew 'shellcheck'
brew 'sqlite'
brew 'swig'
brew 'telnet'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tomcat'
brew 'tree'
brew 'unbound'
brew 'unibilium'
brew 'vault'
brew 'vde'
brew 'vim'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'xz'
brew 'yarn'
brew 'z'
brew 'zlib'
brew 'zplug'
brew 'zsh'
brew 'zsh-completions'

tap 'homebrew/bundle'

tap 'homebrew/cask-fonts'
cask 'font-inconsolata'
cask 'font-meslo-for-powerline'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'

tap 'homebrew/cask-versions'
cask 'sequel-pro-nightly'
cask 'slack-beta'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'alacritty'
cask 'android-studio'
cask 'bartender'
cask 'caffeine'
cask 'choosy'
cask 'cyberduck'
cask 'discord'
cask 'firefox'
cask 'google-backup-and-sync'
cask 'google-japanese-ime'
cask 'hyperswitch'
cask 'insomnia'
cask 'istat-menus'
cask 'iterm2'
cask 'keepassx'
cask 'lastfm'
cask 'minikube'
cask 'quitter'
cask 'sequel-pro'
cask 'spotify'
cask 'vagrant'
cask 'visual-studio-code'
cask 'vlc'
cask 'workplace-chat'
cask 'zoomus'

tap 'argon/mas'

tap 'buo/cask-upgrade'

tap 'heroku/brew'
brew 'heroku'
brew 'heroku-node'

tap 'neovim/neovim'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'sanemat/font'
brew 'ricty', args: ['with-powerline']

# Other Cask applications
cask 'airmail-beta'
cask 'alfred'
cask 'appcleaner'
cask 'bathyscaphe'
cask 'chatwork'
cask 'cooviewer'
cask 'deckset'
cask 'dropbox'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-powerline-symbols'
cask 'font-source-code-pro'
cask 'font-source-han-code-jp'
cask 'google-chrome'
cask 'hyper'
cask 'imageoptim'
cask 'intellij-idea'
cask 'istumbler'
cask 'karabiner-elements'
cask 'kindle'
cask 'licecap'
cask 'pg-commander'
cask 'react-native-debugger'
cask 'skitch'
cask 'timemachineeditor'
cask 'versions'
cask 'vivaldi'
cask 'wireshark'
cask 'xquartz'

# App Store applications
mas '1Password 7 (7.3.1)', id: 1333542190
mas 'Apple Configurator 2 (2.9)', id: 1037126344
mas 'Bear (1.6.15)', id: 1091189122
mas 'BetterSnapTool (1.9)', id: 417375580
mas 'CotEditor (3.7.8)', id: 1024640650
mas 'DaisyDisk (4.7.2)', id: 411643860
mas 'Exporter (2.0)', id: 1099120373
mas 'Howler Timer (1.6)', id: 428846772
mas 'LastPass (4.4.0)', id: 926036361
mas 'LGTM (4.0)', id: 1035132445
mas 'LINE (5.18.2)', id: 539883307
mas 'Monosnap (3.5.10)', id: 540348655
mas 'Reeder (3.2.1)', id: 880001334
mas 'Spark (2.3.9)', id: 1176895641
mas 'Todoist (7.1.3)', id: 585829637
mas 'Tweetbot (2.5.8)', id: 557168941
mas 'WinArchiver Lite (2.5.3)', id: 414855915
mas 'Xcode (10.3)', id: 497799835
mas 'そら案内 (3.4.0)', id: 599799247
