
# tap repositories and their packages

tap 'homebrew/core'
brew 'ansible'
brew 'apr'
brew 'apr-util'
brew 'aspell'
brew 'augeas'
brew 'autoconf'
brew 'autojump'
brew 'automake'
brew 'bash-completion'
brew 'bat'
brew 'bdw-gc'
brew 'berkeley-db'
brew 'boost'
brew 'brotli'
brew 'bsdmake'
brew 'c-ares'
brew 'ca-certificates'
brew 'cairo'
brew 'certbot'
brew 'cmake'
brew 'cmigemo'
brew 'colordiff'
brew 'coreutils'
brew 'cscope'
brew 'ctop'
brew 'dark-mode'
brew 'deno'
brew 'dialog'
brew 'digdag'
brew 'direnv'
brew 'docbook'
brew 'docbook-xsl'
brew 'docker-clean'
brew 'double-conversion'
brew 'eigen'
brew 'elinks'
brew 'exa'
brew 'fasd'
brew 'fd'
brew 'fish'
brew 'fmt'
brew 'folly'
brew 'fontconfig'
brew 'fontforge'
brew 'freetype'
brew 'fribidi'
brew 'fx'
brew 'fzf'
brew 'gcc'
brew 'gdbm'
brew 'gettext'
brew 'gflags'
brew 'gh'
brew 'ghq'
brew 'giflib'
brew 'git'
brew 'glib'
brew 'glog'
brew 'gmp'
brew 'gnu-getopt'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnutls'
brew 'go'
brew 'gobject-introspection'
brew 'gradle'
brew 'graphite2'
brew 'grep'
brew 'guile'
brew 'hadolint'
brew 'harfbuzz'
brew 'hexyl'
brew 'htop'
brew 'hub'
brew 'icu4c'
brew 'iproute2mac'
brew 'isl'
brew 'jemalloc'
brew 'jmeter'
brew 'jpeg'
brew 'jq'
brew 'kompose'
brew 'krb5'
brew 'kubernetes-cli'
brew 'lazygit'
brew 'ldns'
brew 'libcbor'
brew 'libev'
brew 'libevent'
brew 'libffi'
brew 'libfido2'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libidn2'
brew 'libmpc'
brew 'libnghttp2'
brew 'libpng'
brew 'libpthread-stubs'
brew 'libslirp'
brew 'libspiro'
brew 'libssh'
brew 'libssh2'
brew 'libtasn1'
brew 'libtermkey'
brew 'libtiff'
brew 'libtool'
brew 'libuninameslist'
brew 'libunistring'
brew 'libusb'
brew 'libuv'
brew 'libx11'
brew 'libxau'
brew 'libxcb'
brew 'libxdmcp'
brew 'libxext'
brew 'libxrender'
brew 'libyaml'
brew 'llvm'
brew 'lua'
brew 'lua@5.1'
brew 'luajit', args: ['HEAD']
brew 'luajit-openresty'
brew 'luarocks'
brew 'luv'
brew 'lz4'
brew 'lzo'
brew 'm4'
brew 'make'
brew 'mas'
brew 'maven'
brew 'mcrypt'
brew 'mecab'
brew 'mhash'
brew 'mosh'
brew 'mpdecimal'
brew 'mpfr'
brew 'msgpack'
brew 'mycli'
brew 'mysql@5.6'
brew 'mysql@5.7'
brew 'ncurses'
brew 'neovim', args: ['HEAD']
brew 'nettle'
brew 'nghttp2'
brew 'nginx'
brew 'nkf'
brew 'node'
brew 'nodebrew'
brew 'numpy'
brew 'oniguruma'
brew 'openblas'
brew 'openjdk'
brew 'openjdk@11'
brew 'openjdk@8'
brew 'openssl@1.1'
brew 'openvpn'
brew 'p11-kit'
brew 'pango'
brew 'pcre'
brew 'pcre2'
brew 'peco'
brew 'percol'
brew 'perl'
brew 'perl-build'
brew 'pixman'
brew 'pkcs11-helper'
brew 'pkg-config'
brew 'postgresql'
brew 'protobuf'
brew 'pyenv-pip-migrate'
brew 'pyenv-virtualenv'
brew 'python-tabulate'
brew 'python@3.10'
brew 'python@3.7'
brew 'python@3.8'
brew 'python@3.9'
brew 'qemu'
brew 'rainbarf'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'redpen'
brew 'rename'
brew 'ripgrep'
brew 'ruby'
brew 'ruby-build'
brew 'rust'
brew 'rust-analyzer'
brew 's3cmd'
brew 'sbt'
brew 'scala'
brew 'shared-mime-info'
brew 'shellcheck'
brew 'six'
brew 'snappy'
brew 'sqlite'
brew 'subversion'
brew 'svn'
brew 'swig'
brew 'tcl-tk'
brew 'telnet'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tomcat'
brew 'tree'
brew 'tree-sitter'
brew 'unbound'
brew 'unibilium'
brew 'utf8proc'
brew 'vault'
brew 'vde'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'xmlto'
brew 'xorgproto'
brew 'xz'
brew 'z'
brew 'zlib'
brew 'zplug'
brew 'zsh'
brew 'zsh-completions'
brew 'zstd'

tap 'homebrew/bundle'

tap 'homebrew/cask-fonts'
cask 'font-roboto'
cask 'font-hack-nerd-font'
cask 'font-inconsolata'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-meslo-for-powerline'
cask 'font-powerline-symbols'
cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'

tap 'homebrew/cask-versions'
cask 'sequel-pro-nightly'
cask 'slack-beta'
cask 'zulu8'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'adoptopenjdk'
cask 'alacritty'
cask 'alfred'
cask 'android-studio'
cask 'appcleaner'
cask 'authy'
cask 'bartender'
cask 'bathyscaphe'
cask 'bitbar'
cask 'caffeine'
cask 'chatwork'
cask 'choosy'
cask 'cyberduck'
cask 'deckset'
cask 'devutils'
cask 'discord'
cask 'dropbox'
cask 'firefox'
cask 'flipper'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'hyper'
cask 'hyperswitch'
cask 'imageoptim'
cask 'insomnia'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'karabiner-elements'
cask 'keepassx'
cask 'kindle'
cask 'krisp'
cask 'lastfm'
cask 'licecap'
cask 'quitter'
cask 'react-native-debugger'
cask 'reactotron'
cask 'scroll-reverser'
cask 'sketch'
cask 'skitch'
cask 'spotify'
cask 'tableplus'
cask 'teamviewer'
cask 'timemachineeditor'
cask 'tradingview'
cask 'tunnelbear'
cask 'vagrant'
cask 'versions'
cask 'visual-studio-code'
cask 'vivaldi'
cask 'vlc'
cask 'wireshark'
cask 'workplace-chat'
cask 'xquartz'
cask 'zoom'

tap 'adoptopenjdk/openjdk'

tap 'aquasecurity/trivy'
brew 'trivy'

tap 'argon/mas'

tap 'aws/tap'
brew 'aws-sam-cli'
brew 'copilot-cli'

tap 'buo/cask-upgrade'

tap 'github/gh'

tap 'heroku/brew'
brew 'heroku'
brew 'heroku-node'

tap 'kyoshidajp/ghkw'
brew 'ghkw'

tap 'neovim/neovim'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'remind101/formulae'
brew 'assume-role'

tap 'sanemat/font'
brew 'ricty', args: ['with-powerline']

tap 'vectordotdev/brew'
brew 'vector'

# Other Cask applications
cask 'font-source-han-code-jp'
cask 'google-backup-and-sync'

# App Store applications
mas '1Password 7 (7.9.2)', id: 1333542190
mas 'Apple Configurator 2 (2.15)', id: 1037126344
mas 'BetterSnapTool (1.9.5)', id: 417375580
mas 'CommentScreen (1.1.3)', id: 1450950860
mas 'CotEditor (4.0.9)', id: 1024640650
mas 'DaisyDisk (4.21.4)', id: 411643860
mas 'Howler Timer (1.6.1)', id: 428846772
mas 'ImageOptim (1.4.4)', id: 1450716465
mas 'Keynote (11.2)', id: 409183694
mas 'LastPass (4.4.0)', id: 926036361
mas 'LINE (7.5.0)', id: 539883307
mas 'MARKETSPEED (2.9.6)', id: 946680495
mas 'MenubarX (1.1.5)', id: 1575588022
mas 'Monosnap (4.18.0)', id: 540348655
mas 'Numbers (11.2)', id: 409203825
mas 'Pages (11.2)', id: 409201541
mas 'Reeder (3.2.3)', id: 880001334
mas 'Reeder (4.2.8)', id: 1449412482
mas 'Skitch (2.9)', id: 425955336
mas 'Spark (2.11.10)', id: 1176895641
mas 'Streaks (7.1.11)', id: 1493327990
mas 'Todoist (8.0.4)', id: 585829637
mas 'Tweetbot (2.5.8)', id: 557168941
mas 'TweetDeck (3.18)', id: 485812721
mas 'Twitter (8.96)', id: 1482454543
mas 'VOX (3.4.4)', id: 461369673
mas 'WinArchiver Lite (2.5.3)', id: 414855915
mas 'Xcode (13.2.1)', id: 497799835
mas 'そら案内 (4.1.0)', id: 599799247
mas '世界株価ｱﾗｰﾄ (2.4.0)', id: 1273092330
