tap "argon/mas"
tap "buo/cask-upgrade"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask", "https://github.com/caskroom/homebrew-cask"
tap "homebrew/cask-fonts", "https://github.com/caskroom/homebrew-fonts"
tap "homebrew/cask-versions", "https://github.com/caskroom/homebrew-versions"
tap "homebrew/core"
tap "neovim/neovim"
cask "xquartz"
brew "libyaml"
brew "openssl"
brew "sqlite"
brew "python@2"
brew "ansible"
brew "ant"
brew "apr"
brew "apr-util"
brew "autoconf"
brew "autojump"
brew "automake"
brew "gettext"
brew "axel"
brew "bash-completion"
brew "boost"
brew "bsdmake"
brew "chipmunk"
brew "cmake"
brew "cmigemo"
brew "colordiff"
brew "coreutils"
brew "cscope"
brew "ctop"
brew "digdag"
brew "direnv"
brew "docker-clean"
brew "eigen"
brew "elinks"
brew "embulk"
brew "libpng"
brew "freetype"
brew "gmp"
brew "gcc"
brew "ghq"
brew "git"
brew "libffi"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "libunistring"
brew "nettle"
brew "p11-kit"
brew "gnutls"
brew "go"
brew "gradle"
brew "libtool"
brew "graphicsmagick"
brew "grep", args: ["with-default-names"]
brew "hadolint"
brew "heroku"
brew "htop"
brew "httping"
brew "hub"
brew "ilmbase"
brew "imagemagick", args: ["with-liblqr"]
brew "iproute2mac"
brew "jemalloc"
brew "jmeter"
brew "jq"
brew "libevent"
brew "libgpg-error"
brew "libgcrypt"
brew "libiconv"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "libxslt"
brew "llvm"
brew "lua"
brew "luajit"
brew "lynx"
brew "lzo"
brew "macvim"
brew "make"
brew "makedepend"
brew "mas"
brew "maven"
brew "mecab"
brew "mercurial"
brew "mosh"
brew "msgpack"
brew "mycli"
brew "mysql"
brew "mysql@5.6"
brew "neovim"
brew "nginx"
brew "nkf"
brew "nodebrew"
brew "numpy"
brew "opencv"
brew "openvpn"
brew "patchutils"
brew "peco"
brew "perl-build"
brew "pkg-config"
brew "postgresql"
brew "proctools"
brew "pyenv"
brew "pyenv-virtualenv"
brew "qemu"
brew "qt"
brew "rainbarf"
brew "raptor"
brew "rasqal"
brew "ruby-build"
brew "rbenv"
brew "re2"
brew "reattach-to-user-namespace"
brew "redis"
brew "unixodbc"
brew "redland"
brew "redpen"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "s3cmd"
brew "sbt"
brew "scala"
brew "shellcheck"
brew "the_silver_searcher"
brew "tmux"
brew "tomcat"
brew "tree"
brew "unar"
brew "utf8proc"
brew "vault"
brew "vim", args: ["with-luajit"], link: false
brew "w3m"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn"
brew "z"
brew "zeromq"
brew "zlib"
brew "zookeeper"
brew "zplug"
brew "zsh"
brew "zsh-completions"
cask "alfred"
cask "android-studio"
cask "appcleaner"
cask "bartender"
cask "bathyscaphe"
cask "bettertouchtool"
cask "bitbar"
cask "caffeine"
cask "choosy"
cask "cyberduck"
cask "deckset"
cask "dropbox"
cask "firefox"
cask "font-inconsolata"
cask "font-meslo-for-powerline"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-han-code-jp"
cask "github-desktop"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "hyper"
cask "hyperswitch"
cask "ibettercharge"
cask "imageoptim"
cask "insomnia"
cask "intellij-idea"
cask "istat-menus"
cask "istumbler"
cask "iterm2"
cask "keepassx"
cask "kindle"
cask "lastfm"
cask "licecap"
cask "near-lock"
cask "pg-commander"
cask "quitter"
cask "react-native-debugger"
cask "recordit"
cask "sequel-pro"
cask "skype"
cask "slack-beta"
cask "spotify"
cask "vagrant"
cask "versions"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "wireshark"
cask "zoomus"
mas "1Keyboard", id: 766939888
mas "1Password", id: 443987910
mas "Apple Configurator 2", id: 1037126344
mas "Bear", id: 1091189122
mas "Coin Tick", id: 1141688067
mas "CotEditor", id: 1024640650
mas "CryptocurrencyTicker", id: 1251526036
mas "DaisyDisk", id: 411643860
mas "Dash", id: 449589707
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "Howler Timer", id: 428846772
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kobito", id: 896624060
mas "LastPass", id: 926036361
mas "LGTM", id: 1035132445
mas "LimeChat", id: 414030210
mas "LINE", id: 539883307
mas "MenuTab for Facebook", id: 421358730
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Reeder", id: 880001334
mas "RulerSwift", id: 1102341786
mas "Shazam", id: 897118787
mas "Skitch", id: 425955336
mas "SoraAnnai", id: 599799247
mas "StuffIt Expander", id: 919269455
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Tweetbot", id: 557168941
mas "VOX", id: 461369673
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
